# Generated by Django 5.0.14 on 2026-08-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('download_url', models.URLField(max_length=500)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
