# Generated by Django 5.0.14 on 2026-08-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_apprelease_pharmacy_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='strips_per_box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
