# Generated by Django 5.0.14 on 2026-08-31 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_remove_medicine_pack_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='trial_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PharmacyControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master_data.pharmacy')),
            ],
        ),
    ]
