# Generated by Django 5.0.14 on 2026-08-27 03:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Categories',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('dosage_form', models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('DROPS', 'Drops'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('GEL', 'Gel'), ('SPRAY', 'Spray'), ('INHALER', 'Inhaler'), ('PATCH', 'Patch'), ('POWDER', 'Powder'), ('SUPPOSITORY', 'Suppository'), ('OTHER', 'Other')], default='', max_length=20)),
                ('strength', models.CharField(blank=True, default='', max_length=100)),
                ('pack_size', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('default_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('default_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('default_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('default_profit_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_returnable', models.BooleanField(default=True)),
                ('is_refrigerated', models.BooleanField(default=False)),
                ('is_injection', models.BooleanField(default=False)),
                ('medicine_type', models.CharField(choices=[('NORMAL', 'Normal'), ('REFRIGERATED', 'Refrigerated'), ('INJECTION', 'Injection'), ('OTHER', 'Other')], default='NORMAL', max_length=20)),
                ('min_stock_level', models.PositiveIntegerField(default=0)),
                ('max_stock_level', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('reorder_qty', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('distribution_scope', models.CharField(choices=[('ALL', 'All Pharmacies'), ('SELECTED', 'Selected Pharmacies Only')], default='ALL', max_length=10)),
                ('version', models.PositiveIntegerField(db_index=True, default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='master_data.medicinecategory')),
                ('available_to_pharmacies', models.ManyToManyField(blank=True, related_name='scoped_medicines', to='master_data.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master_data.pharmacy')),
            ],
        ),
    ]
