# Generated by Django 5.0.14 on 2026-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_medicine_strips_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='l1_unit_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='l2_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='Number of L1 units in one L2 unit'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='l2_unit_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='l3_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='Number of L2 units in one L3 unit'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='l3_unit_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
