# Generated by Django 5.0.14 on 2026-08-30 10:10

from django.db import migrations


def map_units(apps, schema_editor):
    Medicine = apps.get_model('master_data', 'Medicine')
    for m in Medicine.objects.all():
        df = m.dosage_form or ''
        df = df.upper()
        
        l1, l2, l3 = 'Piece', '', ''
        l2_mult, l3_mult = 1, 1
        
        if df in ['TABLET', 'CAPSULE']:
            l1 = 'Tablet' if df == 'TABLET' else 'Capsule'
            if m.strips_per_box and m.strips_per_box > 0:
                l2 = 'Strip'
                tablets_per_strip = int(m.pack_size / m.strips_per_box) if m.pack_size >= m.strips_per_box else 10
                l2_mult = tablets_per_strip
                l3 = 'Box'
                l3_mult = m.strips_per_box
            else:
                l2 = 'Box'
                l2_mult = m.pack_size or 1
        elif df in ['SYRUP', 'SUSPENSION', 'DROPS', 'LOTION', 'CREAM', 'OINTMENT', 'GEL']:
            l1 = 'Bottle' if df in ['SYRUP', 'SUSPENSION', 'DROPS', 'LOTION'] else 'Tube'
            if m.pack_size and m.pack_size > 1:
                l2 = 'Carton'
                l2_mult = m.pack_size
        elif df in ['INJECTION', 'INFUSION', 'VACCINE']:
            l1 = 'Vial'
            if m.pack_size and m.pack_size > 1:
                l2 = 'Pack'
                l2_mult = m.pack_size
        else:
            if m.unit:
                l1 = m.unit
            if m.pack_size and m.pack_size > 1:
                l2 = 'Pack'
                l2_mult = m.pack_size

        m.l1_unit_name = l1
        m.l2_unit_name = l2
        m.l2_multiplier = l2_mult
        m.l3_unit_name = l3
        m.l3_multiplier = l3_mult
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_medicine_l1_unit_name_medicine_l2_multiplier_and_more'),
    ]

    operations = [
        migrations.RunPython(map_units, reverse_code=migrations.RunPython.noop),
    ]
