# Generated by Django 5.0.14 on 2026-08-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20260830_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='pack_size',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='strips_per_box',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='unit',
        ),
    ]
